---
dependencies: []

galaxy_info:
  description: 'Setup elk beats: filebeat, metricbeat, heartbeat'
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - focal
    - name: Fedora
      versions:
        - 35
  galaxy_tags:
    - elk
    - beats
    - filebeat
    - metricbeat
    - heartbeat